dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: CDiJjMfDo/ZhZBWmU5Lh7mccGqUYBOjqPlCHAhQCelum/mHpg1qYdHI0WfNGZuDl5StJPKOMcZ0NO3Drv+dHcMlxz9oLes5iOEokYhwnxJ/mWabM5UyyYpM/8p0YIJMSLwFU5iT8tgBkS6teQPa6JSpDBJ29PZu+zdLhHdEKKDPiYruDWCUGpGYhMjj3b/wBZn/KUax7CKhSTWX4TcVlWSjiuGQOILPBRtzqiGeY87TBo7HtAkTQZLksF1XqbY4C+1MD157jrHKWq35j9Dn36DfS8o/rrwXG9WONrfDzs8326EvPgUMlz12SGC406K2JkPHegKmy3o69o/uFHsQ68txNZu6y7kziwOh8taXcxor+M/TKb3e9I2RqgxNuKUelbZ93RCBkD5FtC4A4BLbeABbCj2tDOy5ah+0nJ48rHg+lXYKeMuJQtbzmj60DCihJlyf93ILVlL+WadhevYwAkXVl31+1UWB8OvZlNwtlhFwp8OHw3TIOZPf724vDh03gAwq0l9IkbzT38sfxHC9YUMx0rwhqsJXZs3kyLp+3IoP8cn+/2/i5kdZVCxHG6Z5TljqsowNnLQ9T0gWLxikTv4F7y/YnBYmQs6Nw5Hrhj4YS7jqzDJsbMbTdWkUp40vzhJZHDDdblESlq2gnOSERa4rOa7UuLrx3dOw4iLdjnFA=
